### ISSUE TITLE
ArrayAdapter as service and Value Objects

### ISSUE THREAD

**Issue by javierseixas** [whiteoctober/Pagerfanta#160]
Hi everyone!

I'm using Pagerfanta integrated with Hateoas and FOSRest in Symfony. I want to declare a factory which is in charge of returning an instance of an `AdapterInterface` based on the class name passed as an argument. In Symfony the service definition would look like this:

```
services:
    pagerfanta.adapter.factory:
        class: Groupalia\BizApiBundle\Pagination\Pagerfanta\AdapterFactory
    pagerfanta.adapter.array:
        class: Pagerfanta\Adapter\AdapterInterface
        factory_service: pagerfanta.adapter.factory
        factory_method: create
        arguments:
            - "Pagerfanta\Adapter\ArrayAdapter"
```

My problem is that the `ArrayAdapter` is instanced passing the data to the constructor, it is mandatory, and there is not any set method.
I would suggest to include it, but I don't know if there is any other way to do what I want.

Cheers!
